version: '3'
services:
  # Item repository image (the API)
  my_item_repository:
    image: eddast/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - game_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'game_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
  # Postgres image to achieve functionality of API
  game_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
