version: '3'
services:
  # Data Dog monitoring system
  # Based on https://github.com/DataDog/docker-compose-example
  my_datadog_container:
    image: datadog/agent:latest
    links:
      - game_api
    environment:
      - DD_API_KEY=a9ec8ca92f316d3efa77dbfa1d4e0358
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAG=simple-tag-0 env:${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  # The UI - game client
  game_client:
    image: eddast/hgop:game-client-${GIT_COMMIT}
    ports:
    - '4000:4000'
    depends_on:
    - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  # Item repository image (the API)
  game_api:
    image: eddast/hgop:game-api-${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - game_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'game_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
      ENVIRONMENT: ${ENVIRONMENT}
  # Postgres image to achieve functionality of API
  game_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
