version: '3'
services:
  # The UI - game client
  game_client:
    image: eddast/hgop:game-client
    ports:
    - '4000:4000'
    depends_on:
    - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  # Item repository image (the API)
  game_api:
    image: eddast/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - game_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'game_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
  # Postgres image to achieve functionality of API
  game_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root123'
